version: '3'
services:
  jellystat-db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - jellystat-postgres-data:/var/lib/postgresql/data
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      TZ: Asia/Kolkata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'my-secret-jwt-key'
    ports:
      - "3020:3000" #Server Port
    volumes:
      - /mnt/HDD/portainer/jellystat/backup-data/:/backup-data

    depends_on:
      - jellystat-db
    restart: unless-stopped
networks:
  default: